name: Build & Publish
on:
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  builds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Get the version
        id: get_version
        run: echo ::set-output name=RELEASE_VERSION::${GITHUB_REF/refs\/tags\//}
      - name: Build & Publish
        uses: elgohr/Publish-Docker-Github-Action@2.14
        with:
          name: paulhenrill/php-fpm
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: 'latest,7.4,7.4-${{ env.RELEASE_VERSION }}'
          cache: ${{ github.event_name != 'schedule' }}
